apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployapps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
        - image: pro-img
          name: guestbook-ui
          ports:
            - containerPort: 80

